### ISSUE TITLE
Plugin no longer compatible with AdoptOpenJDK

### ISSUE THREAD

**Issue by osh-onstructive** [micronaut-projects/micronaut-gradle-plugin#225]
With the recent addition in version 1.5.1 the addition of the user & group fails with the following:

```
Step 5/11 : COPY layers/application.jar /home/app/application.jar
 ---> a28635710d42
Step 6/11 : RUN test -e /usr/sbin/groupadd && groupadd -r app && adduser -g app app && chown -R app:app /home/app || true
 ---> Running in 317860c6429c
Option g is ambiguous (gecos, gid, group)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups]
[--encrypt-home] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX[_SYSTEM] configuration variable
  --extrausers      uses extra users as the database
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

Removing intermediate container 317860c6429c
 ---> 3363edfed9b9
Step 7/11 : RUN test -e /usr/sbin/addgroup && addgroup app && adduser -G app app -D && chown -R app:app /home/app || true
 ---> Running in 006f6b367336
addgroup: The group `app' already exists.
Removing intermediate container 006f6b367336
 ---> aff8070b8a42
```

We are currently using adoptopenjdk/openjdk15:jre-15.0.2_7 as our base image.

I have tried the latest plugin, and all in-between, but this issue seems to arise in 1.5.1.

**Comment by ilopmar** [comment]
This is already fixed in #221. Please upgrade the plugin to version `1.5.3`

**Comment by osh-onstructive** [comment]
I have tried all versions, it was introduced in 1.5.1, but still exists in 1.5.3 & 2.0.1

**Comment by ilopmar** [comment]
@osh-onstructive can you please upload an app that reproduces the issue?

**Comment by ilopmar** [comment]
Btw, you shouldn't use 2.0.1 in a Micronaut 2.5.x application. That version is only for Micronaut 3.x

**Comment by osh-onstructive** [comment]
[adoptopenjdkissue.zip](https://github.com/micronaut-projects/micronaut-gradle-plugin/files/6738758/adoptopenjdkissue.zip)

Please find attached the project to recreate the issue; key change is setting the base image in the build.gradle file
```
dockerfile {
    baseImage.set("adoptopenjdk:16-jre")
}
```

**Comment by ilopmar** [comment]
You can still define your own base image and it works, the problem is that it won't run as the user defined in the Dockerfile (`app`) because the creating fails (with a warning):

```
> Task :dockerBuild
Building image using context '/home/ivan/workspaces/micronaut-apps/adoptopenjdkissue/build/docker'.
Using Dockerfile '/home/ivan/workspaces/micronaut-apps/adoptopenjdkissue/build/docker/Dockerfile'
Using images 'demo'.
Step 1/9 : FROM adoptopenjdk:16-jre
 ---> 954409133efc
Step 2/9 : WORKDIR /home/app
 ---> Running in 258060260ea5
Removing intermediate container 258060260ea5
 ---> 04837cdde1bf
Step 3/9 : COPY layers/libs /home/app/libs
 ---> 5c5714211cc2
Step 4/9 : COPY layers/resources /home/app/resources
 ---> 8b3fc8e359e0
Step 5/9 : COPY layers/application.jar /home/app/application.jar
 ---> aab6bcbec8ff
Step 6/9 : RUN test -e /usr/sbin/groupadd && groupadd -r app && adduser -g app app && chown -R app:app /home/app || true
 ---> Running in f74f15bb26f2
Option g is ambiguous (gecos, gid, group)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups]
[--encrypt-home] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX[_SYSTEM] configuration variable
  --extrausers      uses extra users as the database
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

Removing intermediate container f74f15bb26f2
 ---> 6589602ec06b
Step 7/9 : RUN test -e /usr/sbin/addgroup && addgroup app && adduser -G app app -D && chown -R app:app /home/app || true
 ---> Running in d205815a7354
addgroup: The group `app' already exists.
Removing intermediate container d205815a7354
 ---> 2894aaca20f6
Step 8/9 : EXPOSE 8080
 ---> Running in 84706e1576df
Removing intermediate container 84706e1576df
 ---> 4fde1e4d374b
Step 9/9 : ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
 ---> Running in 7cb72f306f50
Removing intermediate container 7cb72f306f50
 ---> 2243984cf2fb
Successfully built 2243984cf2fb
Successfully tagged demo:latest
Created image with ID '2243984cf2fb'.

BUILD SUCCESSFUL in 2s
6 actionable tasks: 1 executed, 5 up-to-date
```

I'm starting to think that we need to rollback this change (allowing to run the app as another user) because it's not easy to find a command to create the user and group that works for all the different images.

**Comment by osh-onstructive** [comment]
We also need to run as the "app" user, but we do this in the following way:
```
dockerfile {
  baseImage.set("adoptopenjdk:16-jre")
  instruction "RUN useradd app && chown app -R /home/app"
  instruction "USER app"
  instruction """HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"'"""
}
```

Maybe this should be added to the docs rather than trying to handle each and every flavour of the images.

Unfortunately these commands are appended to the docker file, it would be great if these commands would be piped in earlier.

**Comment by ilopmar** [comment]
I see... As I said it's becoming a mess to try to figure out where to put any additional instructions, create user and group,... that works for every use case and every base image.

I think we should:
- Remove the possibility to add those additional instructions
- Remove the creation of the user/group
- Fix https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/214 which will allow users to use their own `Dockerfile` based on their needs, so we don't need to guess where to put the additional instructions, how to create the user/group,...

Maybe @melix can take a look at the bug so at least there is a workaround even if we don't remove those mentioned features (which I really think we should)

**Comment by osh-onstructive** [comment]
I really like having the plugin generate the docker file for us and it has made the management of the builds much easier, so moving back to a hardcoded Dockerfile seems like a step backwards.

I think what's missing, is that these additional instructions are appended to the wrong part, they could simply be moved somewhere before the 'entrypoint' and then we can achieve the user creation part & adding healthchecks, etc. without having to go back to Dockerfile (and everyone benefits from the constant good development there is here in this plugin)

**Comment by ilopmar** [comment]
So, following your suggestion, the output you would expect would be:

```
FROM adoptopenjdk:16-jre
WORKDIR /home/app
COPY layers/libs /home/app/libs
COPY layers/resources /home/app/resources
COPY layers/application.jar /home/app/application.jar
EXPOSE 8080

-------- Additional instructions --------
RUN useradd app && chown app -R /home/app
USER app
HEALTHCHECK CMD curl -s localhost:8090/health | grep '"status":"UP"'
-----------------------------------------

ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
```

Right?

**Comment by osh-onstructive** [comment]
Yes, like that would be perfect.

**Comment by osh-onstructive** [comment]
Excellent, thanks
